//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miratti
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
